// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
namespace POC_ML
{
    public partial class SalaryPrediction
    {
        /// <summary>
        /// model input class for SalaryPrediction.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"YearsExperience")]
            public float YearsExperience { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Age")]
            public float Age { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Salary")]
            public float Salary { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SalaryPrediction.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"YearsExperience")]
            public float YearsExperience { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"Salary")]
            public float Salary { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SalaryPrediction.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
